[package]
name = "hello_world"
version = "0.1.0"
authors = ["Li Zhuohua <lizhuohua1994@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-kernel-module = { path = ".." }

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
