[package]
name = "hello_world"
version = "0.1.0"
authors = ["Li Zhuohua <lizhuohua1994@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-device-driver = { path = ".." }
